<template>
  <div class="page-wrap pb-28 lg:pb-8"><AdminHeader title="Категории" description="Неактивные категории остаются в истории, но недоступны для новых заявок." />
    <form class="panel mt-6 grid gap-4 p-5 lg:grid-cols-[1fr_2fr_auto] lg:items-end" @submit.prevent="createCategory"><div><label for="new-category-name" class="label">Новая категория</label><input id="new-category-name" v-model.trim="newCategory.name" class="field" required minlength="2" placeholder="Название"></div><div><label for="new-category-description" class="label">Описание</label><input id="new-category-description" v-model.trim="newCategory.description" class="field" required minlength="2" placeholder="Для каких обращений"></div><button class="button-primary" type="submit" :disabled="pendingId === 'new'">{{ pendingId === 'new' ? 'Добавляем…' : 'Добавить' }}</button></form>
    <div class="mt-6 grid gap-4 xl:grid-cols-2"><form v-for="category in categories" :key="category.id" class="panel p-5" @submit.prevent="save(category)"><div class="flex items-start gap-3"><div class="flex-1"><label :for="`name-${category.id}`" class="label">Название</label><input :id="`name-${category.id}`" v-model.trim="category.name" class="field" required minlength="2"></div><label class="mt-8 flex items-center gap-2 text-sm font-semibold"><input v-model="category.isActive" type="checkbox" class="size-4 accent-indigo-600"> Активна</label></div><div class="mt-4"><label :for="`description-${category.id}`" class="label">Описание</label><textarea :id="`description-${category.id}`" v-model.trim="category.description" class="field min-h-20 py-3" required /></div><div class="mt-4 flex items-center justify-between gap-3"><span class="text-xs text-slate-400">{{ category.id }}</span><button class="button-secondary" type="submit" :disabled="pendingId === category.id">{{ pendingId === category.id ? 'Сохраняем…' : 'Сохранить' }}</button></div></form></div>
    <p v-if="message" class="mt-4 text-sm font-semibold" :class="failed ? 'text-rose-700' : 'text-emerald-700'" role="status">{{ message }}</p>
  </div>
</template>
<script setup lang="ts">
import type { CategorySummary } from '#shared/types/domain'
definePageMeta({ middleware: 'admin' }); useSeoMeta({ title: 'Категории' })
const { data } = await useFetch<CategorySummary[]>('/api/admin/categories'); const categories = computed(() => data.value ?? []); const pendingId = ref(''); const message = ref(''); const failed = ref(false); const newCategory = reactive({ name: '', description: '' })
async function createCategory() { pendingId.value = 'new'; message.value = ''; try { const category = await $fetch<CategorySummary>('/api/admin/categories', { method: 'POST', body: { ...newCategory, isActive: true } }); data.value?.push(category); newCategory.name = ''; newCategory.description = ''; failed.value = false; message.value = `${category.name}: категория добавлена.` } catch { failed.value = true; message.value = 'Не удалось добавить категорию.' } finally { pendingId.value = '' } }
async function save(category: CategorySummary) { pendingId.value = category.id; message.value = ''; try { Object.assign(category, await $fetch<CategorySummary>(`/api/admin/categories/${category.id}`, { method: 'PATCH', body: { name: category.name, description: category.description, isActive: category.isActive } })); failed.value = false; message.value = `${category.name}: изменения сохранены.` } catch { failed.value = true; message.value = 'Не удалось сохранить категорию.' } finally { pendingId.value = '' } }
</script>
